#!/usr/bin/env bash
# Instaltion & configuration of HAProxy server

# Install HAProxy
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Add to /etc/haproxy/haproxy.conf
fe="frontend main\n\tbind *:80\n\tmode http\n\tdefault_backend web_servers\n\n"
be="backend web_servers\n\tbalance roundrobin\n\toption forwardfor\n\tserver 4284-web-01 18.234.61.191 check\n\tserver 4284-web-02 52.23.239.31 check\n"
echo -e "\n\n""$fe""$be" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
